{% set name = "manif" %}
{% set version = "0.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/artivis/manif/archive/{{ version }}.tar.gz
    sha256: f3fa37c64c60e708331df7e2c70a49c4b6e4f998fc352cd576b9ca79a8acdfed

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                               # [not win]
    - cmake
  host:
    - eigen


test:
  commands:
    - test -f ${PREFIX}/include/manif/manif.h  # [not win]
    - test -f ${PREFIX}/share/manif/cmake/manifConfig.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\manif\\manif.h (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\share\\manif\\cmake\\manifConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/artivis/manif
  license: MIT
  license_file: LICENSE
  summary: A small C++11 header-only library for Lie theory.

extra:
  recipe-maintainers:
    - traversaro
